### ISSUE TITLE
Some options for "Refactor model references" have the opposite effect

### ISSUE THREAD

**Issue by Simouie** [SnowyMouse/six-shooter#1]
When using Six Shooter to bludgeon tags, references to "model" or "gbxmodel" tags can be changed as well. This feature does work but the effect for some options is opposite of they should be, according to the labels for said options.

The option `Change model references to gbxmodel (base HEK tags need it)` changes references to "gbxmodel" tags to be references to "model" tags. The effect is basically `gbxmodel -> model` instead of `model -> gbxmodel`.

Similarly, the option `Change gbxmodel references to model (Xbox porting)` changes references to "model" tags to be references to "gbxmodel" tags. The effect is basically `model -> gbxmodel` instead of `gbxmodel -> model`.

Relevant code from `tag_bludgeoner.cpp`
```cpp
            options_main_layout->addWidget(new QLabel("Refactor model references:", options_widget), 4, 0);
            options_main_layout->addWidget(this->refactor_model_references = new QComboBox(options_widget), 4, 1);
            this->refactor_model_references->addItem("Do nothing");
            this->refactor_model_references->addItem("Change model references to gbxmodel (base HEK tags need it)", static_cast<uint>(TagBludgeoner::Step::RefactorGbxmodelToModel));
            this->refactor_model_references->addItem("Change gbxmodel references to model (Xbox porting)", static_cast<uint>(TagBludgeoner::Step::RefactorModelToGbxmodel));
```

**Comment by Aerocatia** [comment]
Sorry this was forgotten about, it has been fixed in dc072350d275f1f5d3cabb8e1564f137188bd54d
